---
title: "visualization02"
author: "Yiran Jin"
date: "2026-10-06"
output: html_document
---

```{r}
library(tidyverse)
library(patchwork) #patchwork 是 R 里一个把多个 ggplot 图拼在一起的 package
```

```{r}
library(p8105.datasets)
data("weather_df")
```


```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)
```
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package"
  )+
  scale_y_continuous(
    trans = "sqrt",
    position = "right"
  )
```
lets try some other scales
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15º C", "0", "15"))
```

lets look at color
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package") + 
  scale_color_hue(h = c(100, 300))
```
```{r}
ggp_temp_plot = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package"
  ) + 
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )

ggp_temp_plot
```

## themes
```{r}
ggp_temp_plot + 
  theme(legend.position = "bottom")
```

```{r}
ggp_temp_plot + 
  theme_bw() + #black and white
  theme(legend.position = "bottom")
```

```{r}
ggp_temp_plot + 
  theme_classic() + 
  theme(legend.position = "bottom")
```


```{r}
ggp_temp_plot + 
  ggthemes::theme_excel() + 
  theme(legend.position = "bottom")
```

update the tmax vs date plot
```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) + #不要显示趋势线周围的置信区间
  geom_point(aes(size = prcp), alpha = .75) + # 让点的大小由 prcp(precipitation) 决定
  labs(
    title = "seasonal trends in Max temp",
    x = "Date",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package"
  ) + 
  viridis::scale_color_viridis(discrete = TRUE) + 
  theme_minimal() + 
  theme(legend.position = "bottom")
```

## two more weird but useful plot things
```{r}
central_park_df = 
  weather_df |>
  filter(name == "CentralPark_NY")

molokai_df = 
  weather_df |>
  filter(name =="Molokai_HI")
          
ggplot(molokai_df, aes(x = date, y=tmax, color=name))+
  geom_point() +
  geom_line(data = central_park_df)
```
multiple panels with different plot types
now we have everything we need
```{r}
ggp_tmax_tmin = 
  weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point(alpha = .5) +
  theme(legend.position = "none") 

ggp_prcp_dens = 
  weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .5) + 
  theme(legend.position = "none")

ggp_tmax_date = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

(ggp_tmax_tmin + ggp_prcp_dens) / ggp_tmax_date # take these 2 panels and put them together
```

## data manipulation
start with factors

boxplots

```{r}
weather_df |>
  mutate(name = fct_reorder(name, tmax)) |> # 根据每个地点的 tmax 大小，重新排列 name 这个 factor
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

```{r}
weather_df |>
  mutate(name = forcats::fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> #重新排列 name 这个 factor 的 levels
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```
make that distribtion plot
```{r}
weather_df |>
  select(name, tmax, tmin) |> 
  pivot_longer(
    tmax:tmin,
    names_to = "observation", 
    values_to = "temp") |> 
  ggplot(aes(x = temp, fill = observation)) +
  geom_density(alpha = .5) + 
  facet_grid(~name) + # patchwork 是 R 里一个把多个 ggplot 图拼在一起的 package
  viridis::scale_fill_viridis(discrete = TRUE)
```

make an FAS plot
```{r}
pups_df =
  read_csv(
    "data/FAS_pups.csv", skip = 3, na = c("", ".", "NA")) |>
  janitor::clean_names()

litters_df = 
  read_csv(
     "data/FAS_litters.csv", skip = 3, na = c("", ".", "NA")) |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), 3)

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")

fas_df |>
  select(dose, day_of_tx, starts_with("pd")) |>
  pivot_longer(
    starts_with("pd"),
    names_to = "outcome",
    values_to = "pn_day"
  ) |>
  ggplot(aes( x= dose, y= pn_day)) +
  geom_boxplot() +
  facet_grid(day_of_tx ~ outcome)
    

```

